const test = require('node:test');
const assert = require('node:assert/strict');
const {parseReport,createReadOnlyBridge}=require('../webroot/bridge.js');
const fixture=()=>({schema:2,source:'guizang-native-probe',read_only:true,android:true,effective_uid:0,sdk:'35',model:'AOSP test fixture',soc:'virtual',kernel:'6.x-test',execution:'disabled',freeze_ready:false,capabilities:{cgroup2_membership:true,self_freezer_node:true,binder_node:true,pidfd_open:true,framework_coordinator:false,protection_signals:false,verified_thaw:false}});
function hostWith(callback){const host={};host.ksu={exec:(cmd,options,name)=>callback(host,cmd,options,name)};return host;}
test('default bridge performs no command',async()=>{let called=0;const bridge=createReadOnlyBridge({host:hostWith(()=>called++)});await assert.rejects(bridge.readCapabilities(),/bridge_disabled/);assert.equal(called,0)});
test('only one literal read-only command, no caller arguments',async()=>{const host=hostWith((host,cmd,options,name)=>{assert.equal(cmd,'/data/adb/modules/guizang/bin/guizang-probe --json');assert.equal(options,'{}');host[name](0,JSON.stringify(fixture()))});const result=await createReadOnlyBridge({host,enabled:true}).readCapabilities('anything; dangerous');assert.equal(result.freezeReady,false);assert.equal(result.root,true);assert.deepEqual(Object.keys(host),['ksu']);});
test('concurrent repeated clicks deduplicate the process',async()=>{let call,called=0;const host=hostWith((h,c,o,n)=>{called++;call=()=>h[n](0,JSON.stringify(fixture()))});const bridge=createReadOnlyBridge({host,enabled:true});const a=bridge.readCapabilities(),b=bridge.readCapabilities();assert.equal(a,b);assert.equal(called,1);call();await a;});
test('timeout cleans callback and permits fresh diagnostic retry',async()=>{const host=hostWith(()=>{});const bridge=createReadOnlyBridge({host,enabled:true,timeoutMs:10});await assert.rejects(bridge.readCapabilities(),/probe_timeout/);assert.deepEqual(Object.keys(host),['ksu']);await assert.rejects(bridge.readCapabilities(),/probe_timeout/);});
test('manager exception, error code and malformed output fail closed',async()=>{for(const kind of ['throw','errno','json']){const host=hostWith((h,c,o,n)=>{if(kind==='throw')throw Error('x');h[n](kind==='errno'?1:0,'bad')});await assert.rejects(createReadOnlyBridge({host,enabled:true}).readCapabilities());assert.deepEqual(Object.keys(host),['ksu']);}});
test('no missing, non-Android or optimistic mutation claims accepted',()=>{for(const change of [{android:false},{schema:3},{read_only:false},{freeze_ready:true},{execution:'enabled'},{effective_uid:'0'},{kernel:'bad\ntext'}])assert.throws(()=>parseReport(JSON.stringify({...fixture(),...change})))});
test('capabilities have exact types and execution proof cannot be spoofed',()=>{for(const value of [null,'false',1]){const data=fixture();data.capabilities.verified_thaw=value;assert.throws(()=>parseReport(JSON.stringify(data)))}const data=fixture();data.capabilities.verified_thaw=true;assert.throws(()=>parseReport(JSON.stringify(data)))});
test('oversized input rejected; strings remain data not HTML',()=>{assert.throws(()=>parseReport(' '.repeat(16385)));const data=fixture();data.model='<img src=x onerror=alert(1)>';assert.equal(parseReport(JSON.stringify(data)).model,data.model);});
